name: Simple Docker CI/CD
on:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Verify files
      run: |
        [ -f "script.py" ] || exit 1
        [ -f "requirements.txt" ] || exit 1
        [ -f "Dockerfile" ] || exit 1

  build-and-push:
    runs-on: ubuntu-latest
    needs: check-files
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/lmadikov:latest
          ${{ secrets.DOCKER_USERNAME }}/lmadikov:${{ github.sha }}
