name: Python CI

on: [push, pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Verify files
      run: |
        [ -f "script.py" ] || exit 1
        [ -f "requirements.txt" ] || exit 1
        [ -f "Dockerfile" ] || exit 1
        echo "All required files present"
    
    - name: Install exact versions
      run: |
        python -m pip install --upgrade pip
        pip install flask==1.1.4 werkzeug==1.0.1
    
    - name: Simple functionality test
      run: |
        python -c "
from flask import Flask
app = Flask(__name__)
print('Basic Flask test passed')
"
    
    - name: Test application import
      run: |
        python -c "
from script import app
print('Application imports correctly')
"
