name: Simple Python Test

on: [push, pull_request]

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Check required files exist
      run: |
        if [ ! -f "script.py" ]; then
          echo "Error: script.py not found!"
          exit 1
        fi
        if [ ! -f "requirements.txt" ]; then
          echo "Error: requirements.txt not found!"
          exit 1
        fi
        if [ ! -f "Dockerfile" ]; then
          echo "Error: Dockerfile not found!"
          exit 1
        fi
        echo "All required files exist"
  
  test-libraries:
    runs-on: ubuntu-latest
    needs: check-files
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest
    
    - name: Verify Flask is installed
      run: |
        python -c "import flask; print(f'Flask version: {flask.__version__}')"
    
    - name: Run simple test
      run: |
        python -c "from script import app; print('App imported successfully')"
