name: Python CI

on: [push, pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Verify files exist
      run: |
        [ -f "script.py" ] || { echo "Error: script.py missing"; exit 1; }
        [ -f "requirements.txt" ] || { echo "Error: requirements.txt missing"; exit 1; }
        [ -f "Dockerfile" ] || { echo "Error: Dockerfile missing"; exit 1; }
        echo "All required files present"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Verify Flask installation
      run: |
        python -c "
try:
    import flask
    print('✓ Flask installed successfully')
    print(f'Flask version: {flask.__version__}')
except Exception as e:
    print(f'✗ Flask import failed: {e}')
    exit(1)
"
    
    - name: Test application
      run: |
        python -c "
try:
    from script import app
    print('✓ Application imports successfully')
except Exception as e:
    print(f'✗ Application import failed: {e}')
    exit(1)
"
